### ISSUE TITLE
联调页面标题栏异常

### ISSUE THREAD

**Issue by df13954** [SHPDZY/AndroidUiDemo#1]
![2AD14A4A20E77C6C77A7734D97DDE19D](https://user-images.githubusercontent.com/18607031/133542383-64cb5cdb-8205-4150-bb0d-3868df645de0.jpg)

小米8，Android9.环境

折叠之后，标题离开刘海很近

**Comment by SHPDZY** [comment]
这里只是提供了个方案，没有具体去做适配哦


在2021年09月16日 ***@***.***> 写道：

小米8，Android9.环境

折叠之后，标题离开刘海很近

**Comment by df13954** [comment]
> 这里只是提供了个方案，没有具体去做适配哦 在2021年09月16日 ***@***.***> 写道： 小米8，Android9.环境 折叠之后，标题离开刘海很近 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

OK，明白啦
